/* tslint:disable */
/* eslint-disable */
/**
 * Tutorial Management API
 * This API exposes endpoints to manage tutorials.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: myemail@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * DTO representing a user to be created.
 * @export
 * @interface CreateUserDTO
 */
export interface CreateUserDTO {
    /**
     * Unique username of the user
     * @type {string}
     * @memberof CreateUserDTO
     */
    username: string;
    /**
     * user password
     * @type {string}
     * @memberof CreateUserDTO
     */
    password: string;
}

/**
 * Check if a given object implements the CreateUserDTO interface.
 */
export function instanceOfCreateUserDTO(value: object): value is CreateUserDTO {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function CreateUserDTOFromJSON(json: any): CreateUserDTO {
    return CreateUserDTOFromJSONTyped(json, false);
}

export function CreateUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateUserDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function CreateUserDTOToJSON(json: any): CreateUserDTO {
    return CreateUserDTOToJSONTyped(json, false);
}

export function CreateUserDTOToJSONTyped(value?: CreateUserDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

