/* tslint:disable */
/* eslint-disable */
/**
 * Tutorial Management API
 * This API exposes endpoints to manage tutorials.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: myemail@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * DTO representing an group to be created.
 * @export
 * @interface CreateGroupDTO
 */
export interface CreateGroupDTO {
    /**
     * Group name
     * @type {string}
     * @memberof CreateGroupDTO
     */
    name: string;
    /**
     * Username of the group owner
     * @type {string}
     * @memberof CreateGroupDTO
     */
    owner: string;
}

/**
 * Check if a given object implements the CreateGroupDTO interface.
 */
export function instanceOfCreateGroupDTO(value: object): value is CreateGroupDTO {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('owner' in value) || value['owner'] === undefined) return false;
    return true;
}

export function CreateGroupDTOFromJSON(json: any): CreateGroupDTO {
    return CreateGroupDTOFromJSONTyped(json, false);
}

export function CreateGroupDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGroupDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'],
        'owner': json['owner'],
    };
}

export function CreateGroupDTOToJSON(json: any): CreateGroupDTO {
    return CreateGroupDTOToJSONTyped(json, false);
}

export function CreateGroupDTOToJSONTyped(value?: CreateGroupDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'owner': value['owner'],
    };
}

