/* tslint:disable */
/* eslint-disable */
/**
 * Tutorial Management API
 * This API exposes endpoints to manage tutorials.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: myemail@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Entity representing a group with a unique identifier, name, owner, and members.
 * @export
 * @interface GroupDAO
 */
export interface GroupDAO {
    /**
     * Unique identifier for the group.
     * @type {number}
     * @memberof GroupDAO
     */
    id: number;
    /**
     * Name of the group.
     * @type {string}
     * @memberof GroupDAO
     */
    name: string;
    /**
     * Username of the group owner.
     * @type {string}
     * @memberof GroupDAO
     */
    owner: string;
    /**
     * Set of users who are members of the group.
     * @type {Set<string>}
     * @memberof GroupDAO
     */
    members: Set<string>;
}

/**
 * Check if a given object implements the GroupDAO interface.
 */
export function instanceOfGroupDAO(value: object): value is GroupDAO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('owner' in value) || value['owner'] === undefined) return false;
    if (!('members' in value) || value['members'] === undefined) return false;
    return true;
}

export function GroupDAOFromJSON(json: any): GroupDAO {
    return GroupDAOFromJSONTyped(json, false);
}

export function GroupDAOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupDAO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
        'owner': json['owner'],
        'members': new Set(json['members']),
    };
}

export function GroupDAOToJSON(json: any): GroupDAO {
    return GroupDAOToJSONTyped(json, false);
}

export function GroupDAOToJSONTyped(value?: GroupDAO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'owner': value['owner'],
        'members': Array.from(value['members'] as Set<any>),
    };
}

