/* tslint:disable */
/* eslint-disable */
/**
 * Tutorial Management API
 * This API exposes endpoints to manage tutorials.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: myemail@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupDTO } from './GroupDTO';
import {
    GroupDTOFromJSON,
    GroupDTOFromJSONTyped,
    GroupDTOToJSON,
    GroupDTOToJSONTyped,
} from './GroupDTO';

/**
 * DTO representing a page of Group
 * @export
 * @interface GroupsPaginationDTO
 */
export interface GroupsPaginationDTO {
    /**
     * List of GroupDTOs
     * @type {Array<GroupDTO>}
     * @memberof GroupsPaginationDTO
     */
    list: Array<GroupDTO>;
    /**
     * max elements
     * @type {number}
     * @memberof GroupsPaginationDTO
     */
    max: number;
}

/**
 * Check if a given object implements the GroupsPaginationDTO interface.
 */
export function instanceOfGroupsPaginationDTO(value: object): value is GroupsPaginationDTO {
    if (!('list' in value) || value['list'] === undefined) return false;
    if (!('max' in value) || value['max'] === undefined) return false;
    return true;
}

export function GroupsPaginationDTOFromJSON(json: any): GroupsPaginationDTO {
    return GroupsPaginationDTOFromJSONTyped(json, false);
}

export function GroupsPaginationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupsPaginationDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'list': ((json['list'] as Array<any>).map(GroupDTOFromJSON)),
        'max': json['max'],
    };
}

export function GroupsPaginationDTOToJSON(json: any): GroupsPaginationDTO {
    return GroupsPaginationDTOToJSONTyped(json, false);
}

export function GroupsPaginationDTOToJSONTyped(value?: GroupsPaginationDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'list': ((value['list'] as Array<any>).map(GroupDTOToJSON)),
        'max': value['max'],
    };
}

