/* tslint:disable */
/* eslint-disable */
/**
 * Tutorial Management API
 * This API exposes endpoints to manage tutorials.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: myemail@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * DTO representing user credencials
 * @export
 * @interface LoginUserDTO
 */
export interface LoginUserDTO {
    /**
     * Unique username of the user
     * @type {string}
     * @memberof LoginUserDTO
     */
    username: string;
    /**
     * Users password
     * @type {string}
     * @memberof LoginUserDTO
     */
    password: string;
}

/**
 * Check if a given object implements the LoginUserDTO interface.
 */
export function instanceOfLoginUserDTO(value: object): value is LoginUserDTO {
    if (!('username' in value) || value['username'] === undefined) return false;
    if (!('password' in value) || value['password'] === undefined) return false;
    return true;
}

export function LoginUserDTOFromJSON(json: any): LoginUserDTO {
    return LoginUserDTOFromJSONTyped(json, false);
}

export function LoginUserDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): LoginUserDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'username': json['username'],
        'password': json['password'],
    };
}

export function LoginUserDTOToJSON(json: any): LoginUserDTO {
    return LoginUserDTOToJSONTyped(json, false);
}

export function LoginUserDTOToJSONTyped(value?: LoginUserDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'username': value['username'],
        'password': value['password'],
    };
}

