/* tslint:disable */
/* eslint-disable */
/**
 * Tutorial Management API
 * This API exposes endpoints to manage tutorials.
 *
 * The version of the OpenAPI document: 1.0
 * Contact: myemail@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { UserDTO } from './UserDTO';
import {
    UserDTOFromJSON,
    UserDTOFromJSONTyped,
    UserDTOToJSON,
    UserDTOToJSONTyped,
} from './UserDTO';

/**
 * DTO representing a page of Users
 * @export
 * @interface UsersPaginationDTO
 */
export interface UsersPaginationDTO {
    /**
     * List of UserDTOs
     * @type {Array<UserDTO>}
     * @memberof UsersPaginationDTO
     */
    list: Array<UserDTO>;
    /**
     * max elements
     * @type {number}
     * @memberof UsersPaginationDTO
     */
    max: number;
}

/**
 * Check if a given object implements the UsersPaginationDTO interface.
 */
export function instanceOfUsersPaginationDTO(value: object): value is UsersPaginationDTO {
    if (!('list' in value) || value['list'] === undefined) return false;
    if (!('max' in value) || value['max'] === undefined) return false;
    return true;
}

export function UsersPaginationDTOFromJSON(json: any): UsersPaginationDTO {
    return UsersPaginationDTOFromJSONTyped(json, false);
}

export function UsersPaginationDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): UsersPaginationDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'list': ((json['list'] as Array<any>).map(UserDTOFromJSON)),
        'max': json['max'],
    };
}

export function UsersPaginationDTOToJSON(json: any): UsersPaginationDTO {
    return UsersPaginationDTOToJSONTyped(json, false);
}

export function UsersPaginationDTOToJSONTyped(value?: UsersPaginationDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'list': ((value['list'] as Array<any>).map(UserDTOToJSON)),
        'max': value['max'],
    };
}

